import { NextResponse } from 'next/server'
import { auth } from '@/lib/auth'
import { prisma } from '@/lib/prisma'

export async function GET() {
  const session = await auth()
  if (!session) return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 })
  if (!['SUPER_ADMIN', 'ADMIN'].includes(session.user.role)) {
    return NextResponse.json({ success: false, error: 'Forbidden' }, { status: 403 })
  }

  try {
    // Ensure built-in permissions exist
    await prisma.permission.createMany({
      data: [
        { module: 'dashboard', action: 'view', description: 'View dashboard' },
        { module: 'crm', action: 'view', description: 'View CRM records' },
        { module: 'crm', action: 'create', description: 'Create leads and opportunities' },
        { module: 'crm', action: 'update', description: 'Update CRM records' },
        { module: 'crm', action: 'delete', description: 'Delete CRM records' },
        { module: 'crm', action: 'assign', description: 'Assign leads to users' },
        { module: 'crm', action: 'export', description: 'Export CRM data' },
        { module: 'customers', action: 'view', description: 'View customers' },
        { module: 'customers', action: 'create', description: 'Create customers' },
        { module: 'customers', action: 'update', description: 'Update customers' },
        { module: 'customers', action: 'delete', description: 'Delete customers' },
        { module: 'customers', action: 'export', description: 'Export customer data' },
        { module: 'vendors', action: 'view', description: 'View vendors' },
        { module: 'vendors', action: 'create', description: 'Create vendors' },
        { module: 'vendors', action: 'update', description: 'Update vendors' },
        { module: 'vendors', action: 'delete', description: 'Delete vendors' },
        { module: 'vendors', action: 'export', description: 'Export vendor data' },
        { module: 'sales', action: 'view', description: 'View sales orders and quotes' },
        { module: 'sales', action: 'create', description: 'Create sales orders' },
        { module: 'sales', action: 'update', description: 'Update sales orders' },
        { module: 'sales', action: 'delete', description: 'Delete draft sales orders' },
        { module: 'sales', action: 'approve', description: 'Approve sales orders' },
        { module: 'sales', action: 'reject', description: 'Reject sales orders' },
        { module: 'sales', action: 'cancel', description: 'Cancel sales orders' },
        { module: 'sales', action: 'print', description: 'Print sales documents' },
        { module: 'sales', action: 'export', description: 'Export sales data' },
        { module: 'procurement', action: 'view', description: 'View purchase orders and requests' },
        { module: 'procurement', action: 'create', description: 'Create purchase requests and orders' },
        { module: 'procurement', action: 'update', description: 'Update procurement records' },
        { module: 'procurement', action: 'delete', description: 'Delete draft procurement records' },
        { module: 'procurement', action: 'approve', description: 'Approve purchase orders' },
        { module: 'procurement', action: 'reject', description: 'Reject purchase orders' },
        { module: 'procurement', action: 'cancel', description: 'Cancel purchase orders' },
        { module: 'procurement', action: 'print', description: 'Print procurement documents' },
        { module: 'procurement', action: 'export', description: 'Export procurement data' },
        { module: 'inventory', action: 'view', description: 'View inventory and stock levels' },
        { module: 'inventory', action: 'create', description: 'Create inventory records' },
        { module: 'inventory', action: 'update', description: 'Update inventory records' },
        { module: 'inventory', action: 'delete', description: 'Delete inventory records' },
        { module: 'inventory', action: 'transfer', description: 'Transfer stock between warehouses' },
        { module: 'inventory', action: 'adjust', description: 'Make stock adjustments' },
        { module: 'inventory', action: 'export', description: 'Export inventory data' },
        { module: 'finance', action: 'view', description: 'View financial records' },
        { module: 'finance', action: 'create', description: 'Create financial records' },
        { module: 'finance', action: 'update', description: 'Update financial records' },
        { module: 'finance', action: 'delete', description: 'Delete draft financial records' },
        { module: 'finance', action: 'approve', description: 'Approve financial transactions' },
        { module: 'finance', action: 'journal', description: 'Post journal entries' },
        { module: 'finance', action: 'export', description: 'Export financial data' },
        { module: 'hr', action: 'view', description: 'View HR records' },
        { module: 'hr', action: 'create', description: 'Create employees and HR records' },
        { module: 'hr', action: 'update', description: 'Update HR records' },
        { module: 'hr', action: 'delete', description: 'Delete HR records' },
        { module: 'hr', action: 'manage', description: 'Manage all HR operations' },
        { module: 'hr', action: 'export', description: 'Export HR data' },
        { module: 'payroll', action: 'view', description: 'View payroll records' },
        { module: 'payroll', action: 'create', description: 'Create payroll runs' },
        { module: 'payroll', action: 'approve', description: 'Approve payroll' },
        { module: 'payroll', action: 'export', description: 'Export payroll data' },
        { module: 'pos', action: 'view', description: 'View POS records' },
        { module: 'pos', action: 'create', description: 'Create POS transactions' },
        { module: 'documents', action: 'view', description: 'View documents' },
        { module: 'documents', action: 'create', description: 'Upload documents' },
        { module: 'documents', action: 'delete', description: 'Delete documents' },
        { module: 'documents', action: 'archive', description: 'Archive documents' },
        { module: 'tasks', action: 'view', description: 'View tasks and projects' },
        { module: 'tasks', action: 'create', description: 'Create tasks' },
        { module: 'tasks', action: 'update', description: 'Update tasks' },
        { module: 'tasks', action: 'assign', description: 'Assign tasks to users' },
        { module: 'tasks', action: 'close', description: 'Close completed tasks' },
        { module: 'reports', action: 'view', description: 'View reports' },
        { module: 'reports', action: 'export', description: 'Export report data' },
        { module: 'reports', action: 'configure', description: 'Configure report schedules' },
        { module: 'insights', action: 'view', description: 'View analytics and insights' },
        { module: 'insights', action: 'export', description: 'Export analytics data' },
        { module: 'notifications', action: 'view', description: 'View notifications' },
        { module: 'notifications', action: 'configure', description: 'Configure notification settings' },
        { module: 'workflow', action: 'view', description: 'View workflow instances' },
        { module: 'workflow', action: 'approve', description: 'Approve workflow steps' },
        { module: 'workflow', action: 'reject', description: 'Reject workflow steps' },
        { module: 'workflow', action: 'manage', description: 'Manage workflow definitions' },
        { module: 'workflow', action: 'configure', description: 'Configure workflow templates' },
        { module: 'audit', action: 'view', description: 'View audit logs' },
        { module: 'audit', action: 'export', description: 'Export audit logs' },
        { module: 'fulfillment', action: 'view', description: 'View fulfillment orders and deliveries' },
        { module: 'fulfillment', action: 'create', description: 'Create fulfillment orders and pick lists' },
        { module: 'fulfillment', action: 'update', description: 'Update fulfillment records' },
        { module: 'fulfillment', action: 'delete', description: 'Delete fulfillment records' },
        { module: 'fulfillment', action: 'approve', description: 'Approve fulfillments and shipments' },
        { module: 'fulfillment', action: 'manage', description: 'Manage vehicles, drivers, and warehouse operations' },
        { module: 'users', action: 'view', description: 'View user directory' },
        { module: 'users', action: 'create', description: 'Create user accounts' },
        { module: 'users', action: 'update', description: 'Update user profiles' },
        { module: 'users', action: 'delete', description: 'Delete user accounts' },
        { module: 'users', action: 'suspend', description: 'Suspend or reactivate users' },
        { module: 'users', action: 'configure', description: 'Configure user access settings' },
        { module: 'roles', action: 'view', description: 'View roles' },
        { module: 'roles', action: 'create', description: 'Create custom roles' },
        { module: 'roles', action: 'update', description: 'Update roles' },
        { module: 'roles', action: 'delete', description: 'Delete roles' },
        { module: 'roles', action: 'configure', description: 'Configure role permissions' },
        { module: 'permissions', action: 'view', description: 'View permission definitions' },
        { module: 'permissions', action: 'configure', description: 'Configure system permissions' },
        { module: 'settings', action: 'view', description: 'View system settings' },
        { module: 'settings', action: 'manage', description: 'Manage all system settings' },
        { module: 'settings', action: 'configure', description: 'Configure security and policies' },
      ],
      skipDuplicates: true,
    })

    const [
      settings,
      storeSettings,
      users,
      companies,
      branches,
      numberingSeries,
      permissions,
      roles,
      paymentTerms,
      securityPolicy,
      notificationTemplates,
      workflowDefinitions,
      integrations,
      emailConfig,
      expenseCategories,
      employeeTypes,
    ] = await Promise.all([
      prisma.companySettings.findFirst(),
      prisma.storeSettings.findFirst(),
      prisma.user.findMany({
        select: {
          id: true, name: true, email: true, role: true, isActive: true,
          lastLoginAt: true, createdAt: true,
          userRoles: { select: { customRole: { select: { id: true, name: true } } } },
        },
        orderBy: { createdAt: 'desc' },
      }),
      prisma.company.findMany({
        include: { _count: { select: { branches: true } } },
      }),
      prisma.branch.findMany({
        include: { company: { select: { name: true } } },
      }),
      prisma.numberingSeries.findMany({
        include: { company: { select: { name: true } } },
      }),
      prisma.permission.findMany(),
      prisma.customRole.findMany({
        include: {
          permissions: { include: { permission: true } },
          _count: { select: { userRoles: true } },
        },
      }),
      prisma.paymentTerm.findMany(),
      prisma.securityPolicy.findFirst(),
      prisma.notificationTemplate.findMany(),
      prisma.workflowDefinition.findMany({
        include: {
          steps: { orderBy: { stepOrder: 'asc' } },
          _count: { select: { instances: true } },
        },
      }),
      prisma.integrationConfig.findMany(),
      prisma.emailConfig.findFirst(),
      prisma.expenseCategory.findMany({
        select: { id: true, categoryName: true },
        orderBy: { categoryName: 'asc' },
      }),
      prisma.employeeType.findMany({
        orderBy: { typeName: 'asc' },
      }),
    ])

    return NextResponse.json({
      success: true,
      data: {
        settings,
        storeSettings,
        users,
        companies,
        branches,
        numberingSeries,
        permissions,
        roles,
        paymentTerms,
        securityPolicy,
        notificationTemplates,
        workflowDefinitions,
        integrations,
        emailConfig,
        expenseCategories,
        employeeTypes,
      },
    })
  } catch (err) {
    return NextResponse.json({ success: false, error: process.env.NODE_ENV === 'development' ? (err as Error).message : 'An unexpected error occurred' }, { status: 500 })
  }
}