export const PAKISTAN_CITIES = [
  'Karachi', 'Lahore', 'Islamabad', 'Faisalabad', 'Rawalpindi',
  'Multan', 'Gujranwala', 'Hyderabad', 'Peshawar', 'Quetta',
  'Sialkot', 'Bahawalpur', 'Sargodha', 'Sukkur', 'Larkana',
  'Sheikhupura', 'Gujrat', 'Mardan', 'Sahiwal', 'Okara',
]

export const PAKISTAN_PROVINCES = [
  'Sindh', 'Punjab', 'Khyber Pakhtunkhwa', 'Balochistan', 'Gilgit-Baltistan',
]

export const COMPANY_NAME = 'Pak Enterprise Solutions (Pvt) Ltd'

export const DEPARTMENTS = [
  { name: 'Textile Manufacturing', code: 'TXT' },
  { name: 'Garments Production', code: 'GRM' },
  { name: 'Electronics Assembly', code: 'ELC' },
  { name: 'Food Processing', code: 'FOOD' },
  { name: 'Leather Goods', code: 'LTHR' },
  { name: 'Sales & Marketing', code: 'S&M' },
  { name: 'Finance & Accounts', code: 'FIN' },
  { name: 'Human Resources', code: 'HR' },
  { name: 'Procurement & Supply Chain', code: 'PROC' },
  { name: 'IT & Systems', code: 'IT' },
]

export const DESIGNATIONS = [
  { name: 'Chief Executive Officer', code: 'CEO', level: 10 },
  { name: 'Chief Financial Officer', code: 'CFO', level: 9 },
  { name: 'Operations Director', code: 'OD', level: 8 },
  { name: 'General Manager', code: 'GM', level: 7 },
  { name: 'Senior Manager', code: 'SM', level: 6 },
  { name: 'Manager', code: 'MGR', level: 5 },
  { name: 'Assistant Manager', code: 'AM', level: 4 },
  { name: 'Senior Executive', code: 'SE', level: 3 },
  { name: 'Executive', code: 'EXEC', level: 2 },
  { name: 'Junior Executive', code: 'JR', level: 1 },
  { name: 'Intern', code: 'INT', level: 0 },
]

export const PAKISTANI_MALE_NAMES = [
  'Ahmed', 'Muhammad', 'Ali', 'Hassan', 'Hussain', 'Omar', 'Usman', 'Bilal',
  'Kamran', 'Tariq', 'Faisal', 'Imran', 'Sohail', 'Nadeem', 'Javed',
  'Asif', 'Shahid', 'Rashid', 'Arif', 'Naeem', 'Junaid', 'Adnan',
  'Saqib', 'Farhan', 'Zubair', 'Iqbal', 'Aftab', 'Saleem', 'Waheed', 'Nasir',
]

export const PAKISTANI_FEMALE_NAMES = [
  'Ayesha', 'Fatima', 'Sana', 'Zainab', 'Maryam', 'Hina', 'Nadia', 'Saima',
  'Rabia', 'Farah', 'Sobia', 'Tahira', 'Yasmin', 'Kiran', 'Shazia',
  'Nasreen', 'Parveen', 'Shamim', 'Sakina', 'Bushra', 'Rukhsana', 'Shabnam',
]

export const PAKISTANI_LAST_NAMES = [
  'Khan', 'Sheikh', 'Malik', 'Iqbal', 'Ahmed', 'Hussain', 'Syed', 'Hashmi',
  'Qureshi', 'Chaudhry', 'Butt', 'Bhatti', 'Raja', 'Mirza', 'Awan',
  'Gondal', 'Siddiqui', 'Ansari', 'Usmani', 'Farooqi', 'Naqvi', 'Rizvi',
]

export const VENDOR_NAMES = [
  'Nishat Textile Mills Ltd', 'Gul Ahmed Textile Mills', 'Engro Foods Ltd',
  'Packages Ltd', 'Service Industries Ltd', 'Millat Tractors Ltd',
  'Lucky Cement Ltd', 'Pakistan State Oil', 'Fauji Fertilizer Company',
  'Nestlé Pakistan Ltd', 'Unilever Pakistan Ltd', 'Procter & Gamble Pakistan',
  'Coca-Cola Beverages Pakistan', 'K-Electric Ltd', 'Hub Power Company',
  'Mughal Steel Ltd', 'Ittehad Chemicals Ltd', 'Sitara Chemical Industries',
  'Rashan Karachi (Wholesale)', 'Saima Electronics Saddar',
  'Anwar Khawaja Industries', 'Imperial Electric Works',
  'Sialkot Sports Goods Co', 'Pakistan Surgical Manufacturers',
  'Leather World International', 'Faisalabad Textile Exporters',
  'Lahore Food Distributors', 'Karachi General Trading Co',
  'Al-Fatah Traders', 'Gaziani Enterprises',
  'Sapphire Textile Mills', 'Azgard Nine Ltd', 'Interloop Ltd',
  'Kohinoor Textile Mills', 'Bhanero Textile Mills',
  'Gadoon Textile Mills', 'Khalid Siraj Textile Mills',
  'Sarena Textile Industries', 'Masood Textile Mills', 'Gohar Textile Mills',
  'Haseeb Waqas Sugar Mills', 'Al-Shamsi Traders', 'Pak Agro Industries',
  'Sufi Foods', 'Shan Foods Pvt Ltd', 'National Foods Ltd',
  'Mitchell\'s Fruit Farms', 'Shezan International', 'Meezan Food Industries',
  'Olympia Chemicals Ltd',
]

export const CUSTOMER_NAMES = [
  'Al-Karam Textile Mills', 'Gulshan Fabrics', 'Pak Gulf Traders',
  'Al-Hamd International', 'Star Enterprises Karachi',
  'Punjab Trading Company', 'Sindh General Stores',
  'Khyber Traders', 'Balochistan Wholesale', 'Gilgit Distributors',
  'Karachi Electronics Market', 'Lahore Garments Outlet',
  'Islamabad General Traders', 'Faisalabad Textile Hub',
  'Multan Agricultural Supplies', 'Sialkot Sports World',
  'Gujranwala Hardware Store', 'Hyderabad General Store',
  'Peshawar Wholesale Mart', 'Quetta Dry Fruits',
  'Pak-Saudi Trading Co', 'Gulf-Star Enterprises',
  'Al-Baraka International', 'Mega Mart Pakistan',
  'City Superstore Karachi', 'Chandni Chowk Traders',
  'Anarkali Bazaar Collective', 'Raja Bazaar Wholesale',
  'Defence Shopping Club', 'Clifton Retail Hub',
  'Bahadurabad Electronics', 'Tariq Road Garments',
  'I.I. Chundrigar Business Center', 'Shahrah-e-Faisal Traders',
  'Saddar Bazaar Islamabad', 'Blue Area Commercial',
  'Jinnah Avenue Retailers', 'Gulberg Premier Stores',
  'Mall of Lahore', 'Emporium Mall Partners',
  'Centaurus Retail Group', 'Dolmen Mall Stores',
  'Lucky One Mall Vendors', 'Packages Mall Suppliers',
  'ChenOne Retail Chain', 'Khaadi Retail Stores',
  'Alkaram Studio Outlets', 'Bonanza Satrangi',
  'Junaid Jamshed Stores', 'Sapphire Retail Outlets',
  'Eden City Developers', 'Bahria Town Residents',
  'Gulshan-e-Maymar Community', 'DHA Phase 2-6 Vendors',
  'University Road Booksellers', 'MA Jinnah Road Traders',
  'The Kitchens Karachi', 'Gourmet Foods Lahore',
  'Butt Sweets Suppliers', 'Shahbaz Sweets & Bakers',
  'Pizza Hut Franchise Karachi', 'KFC Franchise Lahore',
  'McDonald\'s Islamabad Partner', 'Burger King Pakistan',
  'Dawn Bread Distributors', 'Shezan Juice Dealers',
  'Nestle Everyday Dealers', 'Shan Masala Wholesale',
  'Mezan Cooking Oil Depot', 'Habib Oil Mills Distributor',
  'National Foods Distributors', 'Coca-Cola Bottlers Karachi',
  'PepsiCo Franchise Lahore', 'Dany Technologies',
  'Computer Zone Lahore', 'Hafeez Centre Karachi',
  'Techno City Islamabad', 'Pak Telecom Mobile - Franchise',
  'JazzCash Agents Network', 'Easypaisa Shop Karachi',
  'UBL Omni Agents', 'HBL Express Counters',
  'MCB Islamic Banking Partners', 'Meezan Bank Branches',
  'Allied Bank Corporate', 'Standard Chartered Pakistan',
  'State Life Insurance Agents', 'Jubilee Life Insurance',
  'EFU General Insurance', 'Askari Insurance Brokers',
  'Pakistan Engineering Services', 'Nespak Consultants',
  'NLC Logistics Partner', 'TCS Private Courier',
  'Leopards Courier Services', 'M&P Express Logistics',
  'Pakistan Post EMS', 'Bykea Delivery Services',
  'Rider Logistic Solutions', 'Daewoo Express Bus Service',
  'Faisal Movers Transport', 'Skyways Transport',
]

export const ITEM_CATEGORIES = [
  { name: 'Cotton Fabric', code: 'COT', parent: 'Textile' },
  { name: 'Readymade Garments', code: 'GAR', parent: 'Textile' },
  { name: 'Yarn & Thread', code: 'YRN', parent: 'Textile' },
  { name: 'Electronics & Components', code: 'ELC', parent: 'Electronics' },
  { name: 'Home Appliances', code: 'HAP', parent: 'Electronics' },
  { name: 'Packaging Materials', code: 'PKG', parent: 'Packaging' },
  { name: 'Food & Beverages', code: 'FOOD', parent: 'FMCG' },
  { name: 'Spices & Condiments', code: 'SPC', parent: 'FMCG' },
  { name: 'Leather Products', code: 'LTH', parent: 'Leather' },
  { name: 'Sports Goods', code: 'SPT', parent: 'Sports' },
  { name: 'Surgical Instruments', code: 'SRG', parent: 'Medical' },
  { name: 'Raw Materials', code: 'RMW', parent: 'Industrial' },
  { name: 'Office Supplies', code: 'OFF', parent: 'Stationery' },
  { name: 'Cleaning Products', code: 'CLN', parent: 'Chemicals' },
  { name: 'Construction Materials', code: 'CON', parent: 'Construction' },
]

export const ITEMS = [
  { name: 'Cotton Fabric - Premium White', category: 'COT', uom: 'Meter', price: 850, vat: 0 },
  { name: 'Cotton Fabric - Dyed Blue', category: 'COT', uom: 'Meter', price: 1200, vat: 0 },
  { name: 'Khaddar Fabric', category: 'COT', uom: 'Meter', price: 650, vat: 0 },
  { name: 'Lawn Fabric - Printed', category: 'COT', uom: 'Meter', price: 950, vat: 0 },
  { name: 'Cambric Fabric', category: 'COT', uom: 'Meter', price: 780, vat: 0 },
  { name: 'Voile Fabric - Digital Print', category: 'COT', uom: 'Meter', price: 1100, vat: 0 },
  { name: 'Kurta Shalwar - Unstitched', category: 'GAR', uom: 'Piece', price: 2500, vat: 0 },
  { name: 'Kurta Shalwar - Stitched', category: 'GAR', uom: 'Piece', price: 4500, vat: 0 },
  { name: 'Shalwar Kameez - Men Formal', category: 'GAR', uom: 'Piece', price: 3500, vat: 0 },
  { name: 'Wash & Wear Suit', category: 'GAR', uom: 'Piece', price: 5500, vat: 0 },
  { name: 'Waistcoat - Men', category: 'GAR', uom: 'Piece', price: 2800, vat: 0 },
  { name: 'Sherwani - Premium', category: 'GAR', uom: 'Piece', price: 15000, vat: 0 },
  { name: 'Dupatta - Printed', category: 'GAR', uom: 'Piece', price: 800, vat: 0 },
  { name: 'Cotton Socks (Pack of 6)', category: 'GAR', uom: 'Pack', price: 450, vat: 0 },
  { name: 'Cotton Yarn 20/1', category: 'YRN', uom: 'Kg', price: 520, vat: 0 },
  { name: 'Polyester Yarn 150D', category: 'YRN', uom: 'Kg', price: 380, vat: 0 },
  { name: 'Cotton Yarn 40/1 Combed', category: 'YRN', uom: 'Kg', price: 680, vat: 0 },
  { name: 'Blended Yarn (50:50)', category: 'YRN', uom: 'Kg', price: 450, vat: 0 },
  { name: 'LED Bulb 12W', category: 'ELC', uom: 'Piece', price: 250, vat: 0 },
  { name: 'LED Bulb 20W', category: 'ELC', uom: 'Piece', price: 380, vat: 0 },
  { name: 'Ceiling Fan 56"', category: 'ELC', uom: 'Piece', price: 5500, vat: 0 },
  { name: 'Electric Iron Dry', category: 'ELC', uom: 'Piece', price: 1500, vat: 0 },
  { name: 'Electric Kettle', category: 'ELC', uom: 'Piece', price: 2200, vat: 0 },
  { name: 'Extension Cord 3m', category: 'ELC', uom: 'Piece', price: 550, vat: 0 },
  { name: 'USB Cable Type-C', category: 'ELC', uom: 'Piece', price: 350, vat: 0 },
  { name: 'Mobile Charger 25W', category: 'ELC', uom: 'Piece', price: 1200, vat: 0 },
  { name: 'Bluetooth Speaker', category: 'ELC', uom: 'Piece', price: 2500, vat: 0 },
  { name: 'Computer Mouse Wireless', category: 'ELC', uom: 'Piece', price: 1800, vat: 0 },
  { name: 'Mechanical Keyboard', category: 'ELC', uom: 'Piece', price: 4500, vat: 0 },
  { name: 'Monitor 24" LED', category: 'ELC', uom: 'Piece', price: 28000, vat: 0 },
  { name: 'Laptop Charger HP', category: 'ELC', uom: 'Piece', price: 3500, vat: 0 },
  { name: 'Router WiFi 6', category: 'ELC', uom: 'Piece', price: 7500, vat: 0 },
  { name: 'UPS 1500VA', category: 'ELC', uom: 'Piece', price: 18000, vat: 0 },
  { name: 'Air Conditioner 1.5 Ton Inverter', category: 'HAP', uom: 'Piece', price: 145000, vat: 0 },
  { name: 'Refrigerator 12 cu.ft', category: 'HAP', uom: 'Piece', price: 85000, vat: 0 },
  { name: 'Washing Machine 10kg', category: 'HAP', uom: 'Piece', price: 95000, vat: 0 },
  { name: 'Microwave Oven 25L', category: 'HAP', uom: 'Piece', price: 25000, vat: 0 },
  { name: 'Water Dispenser Hot/Cold', category: 'HAP', uom: 'Piece', price: 15000, vat: 0 },
  { name: 'Corrugated Box Large', category: 'PKG', uom: 'Piece', price: 85, vat: 0 },
  { name: 'Corrugated Box Medium', category: 'PKG', uom: 'Piece', price: 55, vat: 0 },
  { name: 'Plastic Wrap Roll 500m', category: 'PKG', uom: 'Roll', price: 1200, vat: 0 },
  { name: 'Bubble Wrap Roll 50m', category: 'PKG', uom: 'Roll', price: 2500, vat: 0 },
  { name: 'Tape - Packing 48mmx100m', category: 'PKG', uom: 'Roll', price: 180, vat: 0 },
  { name: 'Basmati Rice Premium 5kg', category: 'FOOD', uom: 'Bag', price: 1200, vat: 0 },
  { name: 'Basmati Rice Super Kernal 10kg', category: 'FOOD', uom: 'Bag', price: 2200, vat: 0 },
  { name: 'Wheat Flour 10kg', category: 'FOOD', uom: 'Bag', price: 950, vat: 0 },
  { name: 'Sugar Refined 1kg', category: 'FOOD', uom: 'Kg', price: 180, vat: 0 },
  { name: 'Cooking Oil 5L', category: 'FOOD', uom: 'Jug', price: 2800, vat: 0 },
  { name: 'Ghee 1kg', category: 'FOOD', uom: 'Pack', price: 520, vat: 0 },
  { name: 'Milk Powder 2kg', category: 'FOOD', uom: 'Pack', price: 2800, vat: 0 },
  { name: 'Tea Leaf Premium 500g', category: 'FOOD', uom: 'Pack', price: 850, vat: 0 },
  { name: 'Canned Chickpeas 400g', category: 'FOOD', uom: 'Can', price: 250, vat: 0 },
  { name: 'Red Chilli Powder 250g', category: 'SPC', uom: 'Pack', price: 350, vat: 0 },
  { name: 'Turmeric Powder 200g', category: 'SPC', uom: 'Pack', price: 280, vat: 0 },
  { name: 'Cumin Seeds 200g', category: 'SPC', uom: 'Pack', price: 250, vat: 0 },
  { name: 'Coriander Powder 200g', category: 'SPC', uom: 'Pack', price: 200, vat: 0 },
  { name: 'Garam Masala 100g', category: 'SPC', uom: 'Pack', price: 320, vat: 0 },
  { name: 'Mixed Spice Biryani 100g', category: 'SPC', uom: 'Pack', price: 180, vat: 0 },
  { name: 'Leather Jacket - Men', category: 'LTH', uom: 'Piece', price: 12000, vat: 0 },
  { name: 'Leather Jacket - Women', category: 'LTH', uom: 'Piece', price: 11000, vat: 0 },
  { name: 'Leather Belt - Men', category: 'LTH', uom: 'Piece', price: 2500, vat: 0 },
  { name: 'Leather Wallet', category: 'LTH', uom: 'Piece', price: 1800, vat: 0 },
  { name: 'Leather Bag - Women', category: 'LTH', uom: 'Piece', price: 8500, vat: 0 },
  { name: 'Leather Briefcase', category: 'LTH', uom: 'Piece', price: 12000, vat: 0 },
  { name: 'Cricket Bat - Kashmir Willow', category: 'SPT', uom: 'Piece', price: 3500, vat: 0 },
  { name: 'Cricket Bat - English Willow', category: 'SPT', uom: 'Piece', price: 12000, vat: 0 },
  { name: 'Cricket Ball (Leather)', category: 'SPT', uom: 'Piece', price: 850, vat: 0 },
  { name: 'Football - Hand Stitched', category: 'SPT', uom: 'Piece', price: 2500, vat: 0 },
  { name: 'Hockey Stick', category: 'SPT', uom: 'Piece', price: 3500, vat: 0 },
  { name: 'Badminton Racket', category: 'SPT', uom: 'Piece', price: 2800, vat: 0 },
  { name: 'Boxing Gloves', category: 'SPT', uom: 'Pair', price: 4500, vat: 0 },
  { name: 'Scalpel Handle No. 3', category: 'SRG', uom: 'Piece', price: 450, vat: 0 },
  { name: 'Scalpel Blade (Pack 100)', category: 'SRG', uom: 'Pack', price: 850, vat: 0 },
  { name: 'Surgical Forceps - Straight', category: 'SRG', uom: 'Piece', price: 1200, vat: 0 },
  { name: 'Artery Forceps', category: 'SRG', uom: 'Piece', price: 1800, vat: 0 },
  { name: 'Scissors - Surgical 6"', category: 'SRG', uom: 'Piece', price: 2200, vat: 0 },
  { name: 'Surgical Needle Holder', category: 'SRG', uom: 'Piece', price: 3500, vat: 0 },
  { name: 'Steel Tray Instrument 12x10', category: 'SRG', uom: 'Piece', price: 2800, vat: 0 },
  { name: 'Suture Thread Silk (Pack 12)', category: 'SRG', uom: 'Pack', price: 1500, vat: 0 },
  { name: 'Raw Cotton Bales', category: 'RMW', uom: 'Bale', price: 28000, vat: 0 },
  { name: 'Polyester Chips', category: 'RMW', uom: 'Kg', price: 220, vat: 0 },
  { name: 'Dyes - Reactive Blue', category: 'RMW', uom: 'Kg', price: 850, vat: 0 },
  { name: 'Steel Rod 12mm x 12m', category: 'RMW', uom: 'Piece', price: 2500, vat: 0 },
  { name: 'Aluminium Sheet 4x8', category: 'RMW', uom: 'Sheet', price: 5500, vat: 0 },
  { name: 'Photocopy Paper A4 (Ream)', category: 'OFF', uom: 'Ream', price: 850, vat: 0 },
  { name: 'Ball Pen Blue (Box 50)', category: 'OFF', uom: 'Box', price: 450, vat: 0 },
  { name: 'File Folder - Kraft', category: 'OFF', uom: 'Piece', price: 45, vat: 0 },
  { name: 'Stapler Small', category: 'OFF', uom: 'Piece', price: 350, vat: 0 },
  { name: 'Staples (Box 5000)', category: 'OFF', uom: 'Box', price: 180, vat: 0 },
  { name: 'Whiteboard Marker (Pack 4)', category: 'OFF', uom: 'Pack', price: 350, vat: 0 },
  { name: 'Sticky Notes 3x3 (Pack 12)', category: 'OFF', uom: 'Pack', price: 280, vat: 0 },
  { name: 'Bleach Liquid 1L', category: 'CLN', uom: 'Bottle', price: 180, vat: 0 },
  { name: 'Hand Soap 5L', category: 'CLN', uom: 'Jug', price: 850, vat: 0 },
  { name: 'Floor Cleaner 1L', category: 'CLN', uom: 'Bottle', price: 280, vat: 0 },
  { name: 'Glass Cleaner 500ml', category: 'CLN', uom: 'Bottle', price: 220, vat: 0 },
  { name: 'Disinfectant Spray 500ml', category: 'CLN', uom: 'Bottle', price: 450, vat: 0 },
  { name: 'Cement Bag 50kg', category: 'CON', uom: 'Bag', price: 1250, vat: 0 },
  { name: 'Sand - Fine (Truck Load)', category: 'CON', uom: 'Ton', price: 8500, vat: 0 },
  { name: 'Bricks (Per 1000)', category: 'CON', uom: 'Thousand', price: 12000, vat: 0 },
  { name: 'Paint Interior 5L', category: 'CON', uom: 'Bucket', price: 4500, vat: 0 },
  { name: 'Paint Exterior 5L', category: 'CON', uom: 'Bucket', price: 6500, vat: 0 },
  { name: 'PVC Pipe 1" x 20ft', category: 'CON', uom: 'Piece', price: 850, vat: 0 },
  { name: 'Tiles Ceramic 12x12 (Box)', category: 'CON', uom: 'Box', price: 2500, vat: 0 },
  { name: 'Marble Sheet 6x4', category: 'CON', uom: 'Sheet', price: 8500, vat: 0 },
  { name: 'Rani Hair Oil 100ml', category: 'FOOD', uom: 'Bottle', price: 320, vat: 0 },
  { name: 'Dishwashing Liquid 500ml', category: 'CLN', uom: 'Bottle', price: 280, vat: 0 },
  { name: 'Toothpaste 150g', category: 'FOOD', uom: 'Piece', price: 250, vat: 0 },
  { name: 'Shampoo 200ml', category: 'FOOD', uom: 'Bottle', price: 550, vat: 0 },
  { name: 'Soap Bar (Pack 5)', category: 'CLN', uom: 'Pack', price: 350, vat: 0 },
  { name: 'Notebook 100 Pages', category: 'OFF', uom: 'Piece', price: 120, vat: 0 },
  { name: 'Rubber Stamp Custom', category: 'OFF', uom: 'Piece', price: 450, vat: 0 },
  { name: 'Mosquito Net Double', category: 'HAP', uom: 'Piece', price: 1500, vat: 0 },
  { name: 'Electric Heater 2000W', category: 'HAP', uom: 'Piece', price: 4500, vat: 0 },
  { name: 'Water Pump 1HP', category: 'ELC', uom: 'Piece', price: 12000, vat: 0 },
  { name: 'Solar Panel 300W', category: 'ELC', uom: 'Piece', price: 25000, vat: 0 },
  { name: 'Battery 150Ah Tubular', category: 'ELC', uom: 'Piece', price: 35000, vat: 0 },
  { name: 'Inverter 3000VA', category: 'ELC', uom: 'Piece', price: 45000, vat: 0 },
  { name: 'Pressure Cooker 5L', category: 'HAP', uom: 'Piece', price: 4500, vat: 0 },
  { name: 'Frying Pan Non-Stick 12"', category: 'HAP', uom: 'Piece', price: 1800, vat: 0 },
  { name: 'Thermos Flask 2L', category: 'HAP', uom: 'Piece', price: 2200, vat: 0 },
  { name: 'Steel Utensil Set 12pc', category: 'HAP', uom: 'Set', price: 8500, vat: 0 },
  { name: 'Plastic Chair Heavy Duty', category: 'OFF', uom: 'Piece', price: 1500, vat: 0 },
  { name: 'Office Desk 4x2', category: 'OFF', uom: 'Piece', price: 12000, vat: 0 },
  { name: 'Office Chair Ergonomic', category: 'OFF', uom: 'Piece', price: 18000, vat: 0 },
  { name: 'Filing Cabinet 4-Drawer', category: 'OFF', uom: 'Piece', price: 25000, vat: 0 },
  { name: 'Air Freshener 300ml', category: 'CLN', uom: 'Bottle', price: 380, vat: 0 },
  { name: 'Wheelbarrow Builders', category: 'CON', uom: 'Piece', price: 5500, vat: 0 },
  { name: 'Shovel Round Mouth', category: 'CON', uom: 'Piece', price: 850, vat: 0 },
  { name: 'Safety Helmet Industrial', category: 'CON', uom: 'Piece', price: 650, vat: 0 },
  { name: 'Safety Gloves (Pair)', category: 'CON', uom: 'Pair', price: 450, vat: 0 },
  { name: 'Extension Ladder 20ft', category: 'CON', uom: 'Piece', price: 8500, vat: 0 },
  { name: 'Aluminium Foil Roll 50m', category: 'PKG', uom: 'Roll', price: 1200, vat: 0 },
  { name: 'Cloth Bag - Shopping 50x70', category: 'PKG', uom: 'Piece', price: 85, vat: 0 },
  { name: 'Plastic Bag - Grocery (Pack 100)', category: 'PKG', uom: 'Pack', price: 250, vat: 0 },
  { name: 'Stretch Film 500mm', category: 'PKG', uom: 'Roll', price: 1800, vat: 0 },
  { name: 'Masking Tape 24mmx50m', category: 'PKG', uom: 'Roll', price: 250, vat: 0 },
  { name: 'Label Sticker A4 (Pack 100)', category: 'OFF', uom: 'Pack', price: 650, vat: 0 },
  { name: 'Carrom Board Standard', category: 'SPT', uom: 'Piece', price: 3500, vat: 0 },
  { name: 'Ludo Game Premium', category: 'SPT', uom: 'Piece', price: 850, vat: 0 },
  { name: 'Chess Set Wooden', category: 'SPT', uom: 'Set', price: 2500, vat: 0 },
  { name: 'Jumping Rope', category: 'SPT', uom: 'Piece', price: 350, vat: 0 },
  { name: 'Dumbbell Set 10kg', category: 'SPT', uom: 'Set', price: 4500, vat: 0 },
  { name: 'Yoga Mat 6mm', category: 'SPT', uom: 'Piece', price: 1800, vat: 0 },
  { name: 'Lunch Box Steel 3-Tier', category: 'HAP', uom: 'Piece', price: 2800, vat: 0 },
  { name: 'Water Bottle 1L Plastic', category: 'HAP', uom: 'Piece', price: 350, vat: 0 },
  { name: 'Vacuum Flask 1L', category: 'HAP', uom: 'Piece', price: 1800, vat: 0 },
  { name: 'Torch LED Rechargeable', category: 'ELC', uom: 'Piece', price: 1200, vat: 0 },
  { name: 'Emergency Light LED', category: 'ELC', uom: 'Piece', price: 2500, vat: 0 },
  { name: 'Electric Bell 6"', category: 'ELC', uom: 'Piece', price: 550, vat: 0 },
  { name: 'Door Lock Mortise 5 Lever', category: 'CON', uom: 'Piece', price: 2500, vat: 0 },
  { name: 'Padlock Heavy Duty', category: 'CON', uom: 'Piece', price: 850, vat: 0 },
  { name: 'Towel Terry Cotton 30x60', category: 'GAR', uom: 'Piece', price: 850, vat: 0 },
  { name: 'Bed Sheet Single Cotton', category: 'GAR', uom: 'Piece', price: 2500, vat: 0 },
  { name: 'Pillow Cotton 20x30', category: 'GAR', uom: 'Piece', price: 650, vat: 0 },
  { name: 'Blanket Single Bed', category: 'GAR', uom: 'Piece', price: 3500, vat: 0 },
  { name: 'Quilt King Size', category: 'GAR', uom: 'Piece', price: 8500, vat: 0 },
]

export const WAREHOUSE_NAMES = [
  { name: 'Karachi Main Warehouse', code: 'KHI-01' },
  { name: 'Lahore Distribution Hub', code: 'LHR-01' },
  { name: 'Islamabad Regional Warehouse', code: 'ISB-01' },
  { name: 'Faisalabad Textile Warehouse', code: 'FSD-01' },
  { name: 'Sialkot Sports & Surgical Store', code: 'SKT-01' },
  { name: 'Multan Cold Storage', code: 'MUX-01' },
  { name: 'Hyderabad Dry Port Warehouse', code: 'HDD-01' },
  { name: 'Peshawar Trade Centre', code: 'PEW-01' },
  { name: 'Quetta Regional Depot', code: 'UET-01' },
  { name: 'Gujranwala Industrial Zone', code: 'GRW-01' },
]

export const PASSWORD_HASH = '$2b$10$Qc9Mo7MPH5lJOBENrJUHyeGb.XUUIJNTxqk/0Ib5j5SlLCUXO.u2y'

export const BANK_NAMES = [
  { name: 'Habib Bank Limited (HBL)', code: 'HBL' },
  { name: 'National Bank of Pakistan', code: 'NBP' },
  { name: 'United Bank Limited (UBL)', code: 'UBL' },
  { name: 'MCB Bank Limited', code: 'MCB' },
  { name: 'Meezan Bank Limited', code: 'MEZ' },
  { name: 'Bank Alfalah Limited', code: 'ALF' },
  { name: 'Allied Bank Limited', code: 'ABL' },
  { name: 'Standard Chartered Pakistan', code: 'SCB' },
]

export const COST_CENTRES = [
  'Textile Division',
  'Garments Division',
  'Electronics Division',
  'Food Division',
  'Sales & Marketing',
  'Administration',
  'Research & Development',
  'Logistics & Distribution',
]

export const HR_LEAVE_TYPES = [
  { code: 'ANNUAL', name: 'Annual Leave', days: 24 },
  { code: 'SICK', name: 'Sick Leave', days: 16 },
  { code: 'CASUAL', name: 'Casual Leave', days: 10 },
  { code: 'EID', name: 'Eid Holiday', days: 5 },
  { code: 'MATERNITY', name: 'Maternity Leave', days: 120 },
  { code: 'HAJJ', name: 'Hajj Leave', days: 40 },
]
